In [95]:
import pandas as pd
import numpy as np
import os

In [96]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [97]:
os.chdir('/content/drive/MyDrive/Hotel_Booking_Analysis')

In [98]:
os.listdir()

['hotel_booking.csv', 'EDA and Cleaning.ipynb', 'clean_hotel_booking.csv']

In [99]:
hotel_df = pd.read_csv('hotel_booking.csv')

## **DATA UNDERSTANDING**

In [100]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  name                            119390 non-null  object
 33  email                           119390 non-null  object
 34  phone-number                    119390 non-null  object
 35  credit_card                     119390 non-null  object
dtypes: float64(4), int64(16), object(16)
memory usage: 32.8+ MB

In [101]:
hotel_df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

In [102]:
hotel_df.duplicated().sum()

np.int64(0)

In [103]:
hotel_df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [104]:
hotel_df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [105]:
hotel_df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [106]:
hotel_df['customer_type'].unique()

array(['Transient', 'Contract', 'Transient-Party', 'Group'], dtype=object)

In [107]:
hotel_df[(hotel_df['market_segment'] == 'Groups') & (hotel_df['customer_type'] == 'Groups')][['market_segment', 'distribution_channel', 'customer_type']]

Empty DataFrame
Columns: [market_segment, distribution_channel, customer_type]
Index: []

In [108]:
hotel_df[(hotel_df['market_segment'] == 'Groups') & (hotel_df['customer_type'] != 'Groups')][['market_segment', 'distribution_channel', 'customer_type']]

       market_segment distribution_channel    customer_type
413            Groups               Direct  Transient-Party
414            Groups               Direct  Transient-Party
415            Groups               Direct  Transient-Party
416            Groups               Direct  Transient-Party
417            Groups               Direct        Transient
...               ...                  ...              ...
119274         Groups                TA/TO  Transient-Party
119275         Groups                TA/TO  Transient-Party
119276         Groups                TA/TO  Transient-Party
119277         Groups                TA/TO  Transient-Party
119278         Groups                TA/TO  Transient-Party

[19811 rows x 3 columns]

In [109]:
hotel_df['total_customer'] = hotel_df['adults'] + hotel_df['children'] + hotel_df['babies']

In [110]:
hotel_df[(hotel_df['adults'] == 0) &
         (hotel_df['children'] == 0) &
         (hotel_df['babies'] == 0)][['adults', 'children', 'babies', 'total_customer', 'reservation_status']]

        adults  children  babies  total_customer reservation_status
2224         0       0.0       0             0.0          Check-Out
2409         0       0.0       0             0.0          Check-Out
3181         0       0.0       0             0.0          Check-Out
3684         0       0.0       0             0.0          Check-Out
3708         0       0.0       0             0.0          Check-Out
...        ...       ...     ...             ...                ...
115029       0       0.0       0             0.0          Check-Out
115091       0       0.0       0             0.0          Check-Out
116251       0       0.0       0             0.0          Check-Out
116534       0       0.0       0             0.0          Check-Out
117087       0       0.0       0             0.0          Check-Out

[180 rows x 5 columns]

In [111]:
hotel_df[(hotel_df['adults'] == 0) &
         (hotel_df['children'] != 0) &
         (hotel_df['babies'] != 0)][['adults', 'children', 'babies', 'total_customer']]

       adults  children  babies  total_customer
46150       0       2.0       1             3.0
81375       0       2.0       1             3.0
90790       0       2.0       1             3.0

In [112]:
hotel_df[(hotel_df['total_customer'] == 0) &
             (hotel_df['reservation_status'] == 'Check-Out')][['adults', 'children', 'babies', 'total_customer', 'adr', 'reservation_status']].sort_values(by = 'adr', ascending = False)

        adults  children  babies  total_customer     adr reservation_status
111406       0       0.0       0             0.0  200.00          Check-Out
101401       0       0.0       0             0.0  168.30          Check-Out
101399       0       0.0       0             0.0  165.38          Check-Out
88439        0       0.0       0             0.0  136.46          Check-Out
115029       0       0.0       0             0.0  100.80          Check-Out
...        ...       ...     ...             ...     ...                ...
111980       0       0.0       0             0.0    0.00          Check-Out
114911       0       0.0       0             0.0    0.00          Check-Out
114908       0       0.0       0             0.0    0.00          Check-Out
115091       0       0.0       0             0.0    0.00          Check-Out
117087       0       0.0       0             0.0    0.00          Check-Out

[155 rows x 6 columns]

In [113]:
hotel_df[['total_customer', 'market_segment', 'distribution_channel']].sort_values(by = 'total_customer', ascending = False).head(15)

       total_customer market_segment distribution_channel
2173             55.0         Direct               Direct
1643             50.0         Direct               Direct
1539             40.0         Direct               Direct
1917             27.0         Direct               Direct
1962             27.0         Direct               Direct
1752             26.0  Offline TA/TO                TA/TO
2003             26.0  Offline TA/TO                TA/TO
2164             26.0  Offline TA/TO                TA/TO
1884             26.0  Offline TA/TO                TA/TO
1587             26.0  Offline TA/TO                TA/TO
2418             20.0         Direct               Direct
2228             20.0         Direct               Direct
46619            12.0      Online TA                TA/TO
328              12.0  Offline TA/TO                TA/TO
2417             10.0         Direct               Direct

In [114]:
hotel_df[(hotel_df['total_customer'] > 5) & (hotel_df['customer_type'] == 'Group')][['adults', 'children', 'babies', 'total_customer', 'market_segment', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

      adults  children  babies  total_customer market_segment customer_type
2173      55       0.0       0            55.0         Direct         Group
1643      50       0.0       0            50.0         Direct         Group
1539      40       0.0       0            40.0         Direct         Group
1917      27       0.0       0            27.0         Direct         Group
1962      27       0.0       0            27.0         Direct         Group
1587      26       0.0       0            26.0  Offline TA/TO         Group
1884      26       0.0       0            26.0  Offline TA/TO         Group
1752      26       0.0       0            26.0  Offline TA/TO         Group
2003      26       0.0       0            26.0  Offline TA/TO         Group
2164      26       0.0       0            26.0  Offline TA/TO         Group
2228      20       0.0       0            20.0         Direct         Group
2418      20       0.0       0            20.0         Direct         Group
2417      10       0.0       0            10.0         Direct         Group
2229       6       0.0       0             6.0         Direct         Group

In [115]:
hotel_df[(hotel_df['total_customer'] > 5) & (hotel_df['customer_type'] != 'Group')][['adults', 'children', 'babies', 'total_customer', 'market_segment', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

,adults,children,babies,total_customer,market_segment,customer_type
328,2,10.0,0,12.0,Offline TA/TO,Contract
46619,2,0.0,10,12.0,Online TA,Transient
78656,1,0.0,9,10.0,Corporate,Transient-Party

In [116]:
hotel_df[(hotel_df['total_customer'] < 5) & (hotel_df['customer_type'] == 'Group')][['adults', 'children', 'babies', 'total_customer', 'market_segment', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

        adults  children  babies  total_customer market_segment customer_type
15303        2       2.0       0             4.0      Online TA         Group
1733         2       2.0       0             4.0      Online TA         Group
87680        2       2.0       0             4.0      Online TA         Group
103970       2       2.0       0             4.0      Online TA         Group
97728        2       2.0       0             4.0      Online TA         Group
...        ...       ...     ...             ...            ...           ...
112103       1       0.0       0             1.0       Aviation         Group
113379       1       0.0       0             1.0      Online TA         Group
76985        0       0.0       0             0.0      Corporate         Group
102185       0       0.0       0             0.0      Online TA         Group
9376         0       0.0       0             0.0  Offline TA/TO         Group

[559 rows x 6 columns]

In [117]:
hotel_df[(hotel_df['total_customer'] < 5) & (hotel_df['customer_type'] == 'Group')][['adults', 'children', 'babies', 'total_customer', 'name', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

,adults,children,babies,total_customer,name,customer_type
15303,2,2.0,0,4.0,Dr. Jessica Jackson,Group
1733,2,2.0,0,4.0,Paul Taylor,Group
87680,2,2.0,0,4.0,Amanda Campbell,Group
103970,2,2.0,0,4.0,Kimberly Mccoy,Group
97728,2,2.0,0,4.0,Courtney Garcia,Group
...,...,...,...,...,...,...
112103,1,0.0,0,1.0,Matthew Franklin,Group
113379,1,0.0,0,1.0,Robert Taylor,Group
76985,0,0.0,0,0.0,Paul Collins,Group
102185,0,0.0,0,0.0,Jesse Smith,Group
9376,0,0.0,0,0.0,Justin Collins,Group

In [118]:
hotel_df[(hotel_df['total_customer'] < 5) & (hotel_df['customer_type'] == 'Contract')][['adults', 'children', 'babies', 'total_customer', 'name', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

,adults,children,babies,total_customer,name,customer_type
79945,2,2.0,0,4.0,Dorothy Ortiz,Contract
79328,2,2.0,0,4.0,John Nolan,Contract
79366,2,2.0,0,4.0,Terry Keller,Contract
79719,2,2.0,0,4.0,David Allen,Contract
79203,2,2.0,0,4.0,Tammy Shelton,Contract
...,...,...,...,...,...,...
79944,1,0.0,0,1.0,Amber Marsh,Contract
40922,0,0.0,0,0.0,Emily Carey,Contract
82266,0,0.0,0,0.0,Joseph Serrano,Contract
77001,0,0.0,0,0.0,Jennifer Nelson,Contract
77003,0,0.0,0,0.0,Melanie Mcknight,Contract

In [119]:
hotel_df[(hotel_df['total_customer'] < 5) & (hotel_df['customer_type'] == 'Transient-Party')][['adults', 'children', 'babies', 'total_customer', 'name', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

,adults,children,babies,total_customer,name,customer_type
97745,2,2.0,0,4.0,Tracy Garcia,Transient-Party
24383,2,2.0,0,4.0,Savannah Weiss,Transient-Party
46654,2,2.0,0,4.0,Melissa Patterson,Transient-Party
33145,3,1.0,0,4.0,Joseph Fowler,Transient-Party
34481,2,2.0,0,4.0,Jessica Good,Transient-Party
...,...,...,...,...,...,...
78257,0,0.0,0,0.0,Kristin Brown,Transient-Party
79077,0,0.0,0,0.0,Kelsey Craig,Transient-Party
88439,0,0.0,0,0.0,Timothy Morris,Transient-Party
88327,0,0.0,0,0.0,Melissa Jenkins,Transient-Party
88017,0,0.0,0,0.0,Mark Marsh,Transient-Party

In [120]:
len(hotel_df[hotel_df['lead_time'] > 31])

79999

In [121]:
len(hotel_df[hotel_df['days_in_waiting_list'] > 31])

2979

In [122]:
hotel_df[(hotel_df['adr'] == 0) & (hotel_df['total_customer'] == 0)][['adults', 'children', 'babies']]

        adults  children  babies
2224         0       0.0       0
2409         0       0.0       0
3181         0       0.0       0
3684         0       0.0       0
3708         0       0.0       0
...        ...       ...     ...
113188       0       0.0       0
114908       0       0.0       0
114911       0       0.0       0
115091       0       0.0       0
117087       0       0.0       0

[149 rows x 3 columns]

In [123]:
hotel_df[(hotel_df['adr'] == 0) & (hotel_df['total_customer'] != 0)][['adults', 'children', 'babies']]

        adults  children  babies
0            2       0.0       0
1            2       0.0       0
125          4       0.0       0
167          2       0.0       0
168          1       0.0       0
...        ...       ...     ...
118631       1       0.0       0
118762       2       1.0       0
118963       2       0.0       0
119102       1       0.0       0
119124       1       0.0       0

[1810 rows x 3 columns]

In [124]:
hotel_df[(hotel_df['previous_bookings_not_canceled'] > 0) & (hotel_df['is_repeated_guest'] == 0)][['is_repeated_guest','previous_bookings_not_canceled']].sort_values(by = 'previous_bookings_not_canceled', ascending = True)

        is_repeated_guest  previous_bookings_not_canceled
106993                  0                               1
13839                   0                               1
13837                   0                               1
13834                   0                               1
13831                   0                               1
...                   ...                             ...
14025                   0                              27
14027                   0                              28
14028                   0                              29
85211                   0                              29
14029                   0                              30

[782 rows x 2 columns]

In [125]:
hotel_df[(hotel_df['previous_bookings_not_canceled'] == 0) & (hotel_df['is_repeated_guest'] == 1)][['is_repeated_guest','previous_bookings_not_canceled']].sort_values(by = 'previous_bookings_not_canceled', ascending = True)

        is_repeated_guest  previous_bookings_not_canceled
111190                  1                               0
111027                  1                               0
110870                  1                               0
109493                  1                               0
109344                  1                               0
...                   ...                             ...
117701                  1                               0
117961                  1                               0
118029                  1                               0
119070                  1                               0
14681                   1                               0

[972 rows x 2 columns]

In [126]:
hotel_df[((hotel_df['previous_cancellations'] == 0) &
         (hotel_df['previous_bookings_not_canceled'] == 0)) &
         (hotel_df['is_repeated_guest'] == 1)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
15446,0,0,1
15797,0,0,1
16366,0,0,1
16375,0,0,1
16517,0,0,1
...,...,...,...
117295,0,0,1
117701,0,0,1
117961,0,0,1
118029,0,0,1
119070,0,0,1

In [127]:
hotel_df[((hotel_df['previous_cancellations'] == 0) &
         (hotel_df['previous_bookings_not_canceled'] == 0)) &
         (hotel_df['is_repeated_guest'] == 0)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
0,0,0,0
1,0,0,0
2,0,0,0
3,0,0,0
4,0,0,0
...,...,...,...
119385,0,0,0
119386,0,0,0
119387,0,0,0
119388,0,0,0
119389,0,0,0

In [128]:
hotel_df[((hotel_df['previous_cancellations'] > 0) &
         (hotel_df['previous_bookings_not_canceled'] == 0)) &
         (hotel_df['is_repeated_guest'] == 1)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
14681,1,0,1
14777,1,0,1
14817,1,0,1
14823,1,0,1
14826,1,0,1
...,...,...,...
82293,1,0,1
82313,1,0,1
82651,1,0,1
82715,1,0,1
82735,1,0,1

In [129]:
hotel_df[((hotel_df['previous_cancellations'] == 0) &
         (hotel_df['previous_bookings_not_canceled'] > 0)) &
         (hotel_df['is_repeated_guest'] == 1)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
13937,0,1,1
14881,0,2,1
14882,0,3,1
14883,0,1,1
14900,0,1,1
...,...,...,...
114139,0,1,1
114873,0,1,1
117319,0,1,1
117424,0,1,1
117841,0,1,1

In [130]:
hotel_df[((hotel_df['previous_cancellations'] > 0) &
         (hotel_df['previous_bookings_not_canceled'] == 0)) &
         (hotel_df['is_repeated_guest'] == 0)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
13988,1,0,0
13989,1,0,0
14125,1,0,0
14181,1,0,0
14182,1,0,0
...,...,...,...
82943,1,0,0
82944,1,0,0
82945,1,0,0
83088,3,0,0
91692,1,0,0

In [131]:
hotel_df[((hotel_df['previous_cancellations'] == 0) &
         (hotel_df['previous_bookings_not_canceled'] > 0)) &
         (hotel_df['is_repeated_guest'] == 0)][['previous_cancellations', 'previous_bookings_not_canceled', 'is_repeated_guest']]

,previous_cancellations,previous_bookings_not_canceled,is_repeated_guest
13803,0,1,0
13804,0,2,0
13808,0,1,0
13813,0,1,0
13814,0,2,0
...,...,...,...
116048,0,1,0
116809,0,1,0
118581,0,1,0
118651,0,1,0
118654,0,1,0

In [132]:
hotel_df[hotel_df['customer_type'] == 'Transient'][['total_customer', 'market_segment', 'distribution_channel', 'customer_type']].sort_values(by = 'total_customer', ascending = False)

        total_customer market_segment distribution_channel customer_type
46619             12.0      Online TA                TA/TO     Transient
17253              5.0         Direct               Direct     Transient
112700             5.0         Direct               Direct     Transient
82556              5.0         Groups                TA/TO     Transient
103285             5.0      Online TA                TA/TO     Transient
...                ...            ...                  ...           ...
101329             0.0      Online TA                TA/TO     Transient
99260              0.0      Corporate            Corporate     Transient
99774              0.0         Direct               Direct     Transient
100487             0.0      Online TA                TA/TO     Transient
100780             0.0         Groups                TA/TO     Transient

[89613 rows x 4 columns]

In [133]:
hotel_df['reservation_status'].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [134]:
hotel_df['total_stays_nights'] = hotel_df['stays_in_weekend_nights'] + hotel_df['stays_in_week_nights']

In [135]:
hotel_df['arrival_date'] = hotel_df['arrival_date_year'].astype(str) + '-' + hotel_df['arrival_date_month'] + '-' + hotel_df['arrival_date_day_of_month'].astype(str)

In [136]:
hotel_df['reservation_status_date'] = pd.to_datetime(hotel_df['reservation_status_date'], format = '%Y-%m-%d')

In [137]:
hotel_df['arrival_date'] = pd.to_datetime(hotel_df['arrival_date'], format = '%Y-%B-%d')

In [138]:
hotel_df['expected_checkout_date'] = hotel_df['arrival_date'] + pd.to_timedelta(hotel_df['total_stays_nights'], unit = 'D')

In [139]:
hotel_df[(hotel_df['adults'] == 0) &
         (hotel_df['children'] == 0) &
         (hotel_df['babies'] == 0) &
         (hotel_df['total_stays_nights'] == 0)][[
             'adults', 'children', 'babies', 'total_customer', 'total_stays_nights', 'reservation_status']].sort_values(by = 'total_stays_nights', ascending = False)

,adults,children,babies,total_customer,total_stays_nights,reservation_status
2409,0,0.0,0,0.0,0,Check-Out
4127,0,0.0,0,0.0,0,Canceled
9376,0,0.0,0,0.0,0,Canceled
61244,0,0.0,0,0.0,0,Canceled
61245,0,0.0,0,0.0,0,Canceled
...,...,...,...,...,...,...
111709,0,0.0,0,0.0,0,Check-Out
111710,0,0.0,0,0.0,0,Check-Out
113188,0,0.0,0,0.0,0,Check-Out
114908,0,0.0,0,0.0,0,Check-Out
114911,0,0.0,0,0.0,0,Check-Out

In [140]:
hotel_df[(hotel_df['adults'] == 0) &
         (hotel_df['children'] == 0) &
         (hotel_df['babies'] == 0) &
         (hotel_df['total_stays_nights'] != 0)][[
             'adults', 'children', 'babies', 'total_customer', 'total_stays_nights', 'reservation_status']].sort_values(by = 'total_stays_nights', ascending = False)

,adults,children,babies,total_customer,total_stays_nights,reservation_status
101794,0,0.0,0,0.0,57,Check-Out
88017,0,0.0,0,0.0,49,Check-Out
106561,0,0.0,0,0.0,43,Check-Out
41020,0,0.0,0,0.0,29,Check-Out
98046,0,0.0,0,0.0,28,Check-Out
...,...,...,...,...,...,...
93397,0,0.0,0,0.0,1,Check-Out
102129,0,0.0,0,0.0,1,Check-Out
111406,0,0.0,0,0.0,1,Check-Out
111980,0,0.0,0,0.0,1,Check-Out
115091,0,0.0,0,0.0,1,Check-Out

In [141]:
hotel_df[(hotel_df['reservation_status'] == 'No-Show') &
         (hotel_df['total_stays_nights'] == 0) &
         (hotel_df['reservation_status_date'] != hotel_df['arrival_date'])][['arrival_date', 'total_stays_nights', 'reservation_status_date']]

Empty DataFrame
Columns: [arrival_date, total_stays_nights, reservation_status_date]
Index: []

In [142]:
hotel_df[(hotel_df['reservation_status'] == 'No-Show') &
         (hotel_df['total_stays_nights'] > 0) &
         (hotel_df['reservation_status_date'] != hotel_df['arrival_date'])][['arrival_date', 'total_stays_nights', 'reservation_status_date']].sort_values(by = 'total_stays_nights', ascending = True)

     arrival_date  total_stays_nights reservation_status_date
7035   2016-07-17                   7              2016-03-28

In [143]:
hotel_df[(hotel_df['reservation_status'] == 'Canceled') &
         (hotel_df['total_stays_nights'] == 0) &
         (hotel_df['reservation_status_date'] != hotel_df['arrival_date'])][['arrival_date', 'total_stays_nights', 'reservation_status_date']]

Empty DataFrame
Columns: [arrival_date, total_stays_nights, reservation_status_date]
Index: []

In [144]:
hotel_df[(hotel_df['reservation_status'] == 'Canceled') &
         (hotel_df['total_stays_nights'] > 0) &
         (hotel_df['reservation_status_date'] != hotel_df['arrival_date']) &
         (hotel_df['reservation_status_date'] != hotel_df['expected_checkout_date'])][['arrival_date', 'total_stays_nights', 'reservation_status_date']].sort_values(by = 'total_stays_nights', ascending = True)

      arrival_date  total_stays_nights reservation_status_date
89165   2017-06-08                   1              2017-06-07
87688   2016-11-25                   1              2016-11-07
87687   2016-11-25                   1              2016-11-07
87647   2016-05-26                   1              2016-05-06
86275   2017-07-13                   1              2017-07-12
...            ...                 ...                     ...
46694   2016-01-15                  30              2016-01-12
9334    2016-11-12                  30              2016-10-19
5344    2016-04-25                  33              2016-04-19
3820    2016-01-12                  42              2015-12-04
9839    2017-01-10                  56              2016-10-31

[42136 rows x 3 columns]

In [145]:
hotel_df[(hotel_df['reservation_status'] == 'Check-Out' ) &
        (hotel_df['reservation_status_date'] == hotel_df['expected_checkout_date'])][[
            'arrival_date',
            'total_stays_nights',
            'reservation_status',
            'reservation_status_date',
            'expected_checkout_date']]

,arrival_date,total_stays_nights,reservation_status,reservation_status_date,expected_checkout_date
0,2015-07-01,0,Check-Out,2015-07-01,2015-07-01
1,2015-07-01,0,Check-Out,2015-07-01,2015-07-01
2,2015-07-01,1,Check-Out,2015-07-02,2015-07-02
3,2015-07-01,1,Check-Out,2015-07-02,2015-07-02
4,2015-07-01,2,Check-Out,2015-07-03,2015-07-03
...,...,...,...,...,...
119385,2017-08-30,7,Check-Out,2017-09-06,2017-09-06
119386,2017-08-31,7,Check-Out,2017-09-07,2017-09-07
119387,2017-08-31,7,Check-Out,2017-09-07,2017-09-07
119388,2017-08-31,7,Check-Out,2017-09-07,2017-09-07
119389,2017-08-29,9,Check-Out,2017-09-07,2017-09-07

In [146]:
len(hotel_df[(hotel_df['reservation_status'] == 'Check-Out' ) &
        (hotel_df['reservation_status_date'] != hotel_df['expected_checkout_date'])][[
            'arrival_date',
            'total_stays_nights',
            'reservation_status',
            'reservation_status_date',
            'expected_checkout_date']])

27

In [147]:
hotel_df[(hotel_df['is_canceled'] == 1) &(hotel_df['reservation_status'] == 'Check-Out')][['is_canceled', 'reservation_status']]

Empty DataFrame
Columns: [is_canceled, reservation_status]
Index: []

In [148]:
hotel_df[(hotel_df['is_canceled'] == 0) &(hotel_df['reservation_status'] != 'Check-Out')][['is_canceled', 'reservation_status']]

Empty DataFrame
Columns: [is_canceled, reservation_status]
Index: []

In [149]:
hotel_df[(hotel_df['adults'] == 0) &
         (hotel_df['children'] != 0) &
         (hotel_df['babies'] != 0)][['adults', 'children', 'babies']]

       adults  children  babies
46150       0       2.0       1
81375       0       2.0       1
90790       0       2.0       1

In [150]:
hotel_df[(hotel_df['adults'] == 0) &
         ((hotel_df['children'] != 0) |
          (hotel_df['babies'] != 0))][['adults', 'children', 'babies', 'market_segment', 'distribution_channel', 'customer_type', 'adr']]

,adults,children,babies,market_segment,distribution_channel,customer_type,adr
40984,0,3.0,0,Direct,Direct,Transient-Party,9.00
41048,0,2.0,0,Online TA,TA/TO,Transient-Party,6.00
41446,0,2.0,0,Direct,Direct,Transient-Party,6.00
41952,0,2.0,0,Complementary,Direct,Transient,0.00
45158,0,2.0,0,Offline TA/TO,TA/TO,Transient-Party,6.00
...,...,...,...,...,...,...,...
117204,0,2.0,0,Online TA,TA/TO,Transient,98.85
117274,0,2.0,0,Online TA,TA/TO,Transient,93.64
117303,0,2.0,0,Online TA,TA/TO,Transient,98.85
117453,0,2.0,0,Online TA,TA/TO,Transient,121.88
118200,0,3.0,0,Direct,Direct,Transient-Party,6.00

In [151]:
hotel_df['reservation_status'].unique()

array(['Check-Out', 'Canceled', 'No-Show'], dtype=object)

In [152]:
hotel_df[(hotel_df['adults'] == 0) &
         ((hotel_df['children'] != 0) |
          (hotel_df['babies'] != 0)) & (hotel_df['reservation_status'] == 'Check-Out')][['adults', 'children', 'babies', 'market_segment', 'distribution_channel', 'customer_type', 'adr']]

,adults,children,babies,market_segment,distribution_channel,customer_type,adr
40984,0,3.0,0,Direct,Direct,Transient-Party,9.00
41048,0,2.0,0,Online TA,TA/TO,Transient-Party,6.00
41446,0,2.0,0,Direct,Direct,Transient-Party,6.00
41952,0,2.0,0,Complementary,Direct,Transient,0.00
46150,0,2.0,1,Online TA,TA/TO,Transient-Party,77.00
...,...,...,...,...,...,...,...
117204,0,2.0,0,Online TA,TA/TO,Transient,98.85
117274,0,2.0,0,Online TA,TA/TO,Transient,93.64
117303,0,2.0,0,Online TA,TA/TO,Transient,98.85
117453,0,2.0,0,Online TA,TA/TO,Transient,121.88
118200,0,3.0,0,Direct,Direct,Transient-Party,6.00

In [153]:
hotel_df[(hotel_df['adults'] == 0) &
         ((hotel_df['children'] != 0) |
          (hotel_df['babies'] != 0)) & (hotel_df['reservation_status'] == 'Canceled')][['adults', 'children', 'babies', 'market_segment', 'distribution_channel', 'customer_type', 'adr']]

,adults,children,babies,market_segment,distribution_channel,customer_type,adr
45158,0,2.0,0,Offline TA/TO,TA/TO,Transient-Party,6.00
46132,0,3.0,0,Online TA,TA/TO,Transient-Party,104.25
46196,0,2.0,0,Online TA,TA/TO,Transient-Party,77.25
46688,0,2.0,0,Online TA,TA/TO,Transient-Party,77.25
46740,0,2.0,0,Online TA,TA/TO,Transient-Party,77.25
...,...,...,...,...,...,...,...
71667,0,2.0,0,Online TA,TA/TO,Transient,90.05
73136,0,2.0,0,Online TA,TA/TO,Transient,96.25
73185,0,2.0,0,Online TA,TA/TO,Transient,104.05
82201,0,2.0,0,Direct,Direct,Transient-Party,7.80
82648,0,2.0,0,Online TA,TA/TO,Transient-Party,6.00

In [154]:
hotel_df[(hotel_df['adults'] == 0) &
         ((hotel_df['children'] != 0) |
          (hotel_df['babies'] != 0)) & (hotel_df['reservation_status'] == 'No-Show')][['adults', 'children', 'babies', 'market_segment', 'distribution_channel', 'customer_type', 'adr']]

,adults,children,babies,market_segment,distribution_channel,customer_type,adr
56754,0,2.0,0,Online TA,TA/TO,Transient,124.25
57038,0,2.0,0,Online TA,TA/TO,Transient,124.25
81375,0,2.0,1,Direct,Direct,Transient,80.75

## **CLEANING**

In [155]:
hotel_df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
total_customer                         4
total_stays_nights                     0
arrival_date                           0
expected_checkout_date                 0
dtype: int64

In [156]:
hotel_df = hotel_df[hotel_df['adr'] >= 0]

In [157]:
hotel_df[hotel_df['adr'] < 0]

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, company, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date, name, email, phone-number, credit_card, total_customer, total_stays_nights, arrival_date, expected_checkout_date]
Index: []

[0 rows x 40 columns]

In [158]:
hotel_df = hotel_df[(hotel_df['adults'] + hotel_df['children'] + hotel_df['babies']) > 0]

In [159]:
hotel_df[(hotel_df['adults'] == 0) & (hotel_df['children'] == 0) & (hotel_df['babies'] == 0)][['adults', 'children', 'babies']]

Empty DataFrame
Columns: [adults, children, babies]
Index: []

In [160]:
hotel_df = hotel_df[ ~(
    (hotel_df['adults'] == 0) &
    ((hotel_df['children'] != 0) | (hotel_df['babies'] != 0)) &
    (hotel_df['reservation_status'] == 'Check-Out')
)]

In [161]:
hotel_df[(hotel_df['adults'] == 0) &
         ((hotel_df['children'] != 0) |
          (hotel_df['babies'] != 0)) & (hotel_df['reservation_status'] == 'Check-Out')][['adults', 'children', 'babies', 'market_segment', 'distribution_channel', 'customer_type', 'adr']]

Empty DataFrame
Columns: [adults, children, babies, market_segment, distribution_channel, customer_type, adr]
Index: []

In [162]:
hotel_df[hotel_df['country'].isna()][['country', 'reservation_status']].groupby('reservation_status').size()

reservation_status
Canceled      53
Check-Out    421
No-Show        4
dtype: int64

In [163]:
hotel_df['country'] = hotel_df['country'].fillna('Unknown')

In [164]:
hotel_df['country'].isna().sum()

np.int64(0)

In [165]:
hotel_df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Aviation'], dtype=object)

In [166]:
hotel_df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [167]:
hotel_df[(hotel_df['agent'].isna()) &
         (hotel_df['distribution_channel'] == 'TA/TO')][['agent', 'market_segment', 'distribution_channel']]

        agent market_segment distribution_channel
541       NaN      Online TA                TA/TO
851       NaN      Online TA                TA/TO
971       NaN  Offline TA/TO                TA/TO
1562      NaN      Online TA                TA/TO
1970      NaN      Online TA                TA/TO
...       ...            ...                  ...
116160    NaN      Online TA                TA/TO
116946    NaN      Online TA                TA/TO
117066    NaN      Online TA                TA/TO
117075    NaN      Online TA                TA/TO
118385    NaN         Direct                TA/TO

[3156 rows x 3 columns]

In [168]:
hotel_df[(hotel_df['agent'].isna()) &
         (hotel_df['distribution_channel'] != 'TA/TO')][['agent', 'market_segment', 'distribution_channel']]

        agent market_segment distribution_channel
0         NaN         Direct               Direct
1         NaN         Direct               Direct
2         NaN         Direct               Direct
6         NaN         Direct               Direct
18        NaN      Corporate            Corporate
...       ...            ...                  ...
119124    NaN  Complementary            Corporate
119151    NaN         Direct               Direct
119166    NaN         Direct               Direct
119215    NaN         Direct               Direct
119248    NaN      Corporate            Corporate

[13109 rows x 3 columns]

In [169]:
hotel_df['agent'] = hotel_df['agent'].astype('object')

In [170]:
hotel_df.loc[hotel_df['agent'].isna() &
             (hotel_df['distribution_channel'] != 'TA/TO'),
             'agent'
            ] = 'No Agent'

In [171]:
hotel_df.loc[hotel_df['agent'].isna() &
             (hotel_df['distribution_channel'] == 'TA/TO'),
             'agent'
            ] = 'Unknown'

In [172]:
hotel_df['agent'].isna().sum()

np.int64(0)

In [173]:
hotel_df[(hotel_df['company'].notna())][['company', 'market_segment', 'distribution_channel', 'customer_type']].groupby('market_segment').size()

market_segment
Aviation          210
Complementary     304
Corporate        4459
Direct            207
Groups           1389
Offline TA/TO     104
Online TA          94
dtype: int64

In [174]:
hotel_df[(hotel_df['company'].notna())][['company', 'market_segment', 'distribution_channel', 'customer_type']].groupby('distribution_channel').size()

distribution_channel
Corporate    5061
Direct        799
GDS             1
TA/TO         906
dtype: int64

In [175]:
hotel_df[(hotel_df['company'].notna())][['company', 'market_segment', 'distribution_channel', 'customer_type']].groupby('customer_type').size()

customer_type
Contract              5
Group                47
Transient          4131
Transient-Party    2584
dtype: int64

In [176]:
hotel_df['company'].nunique()

348

In [177]:
hotel_df[['company']].groupby('company').size().sort_values(ascending = False)

company
40.0     924
223.0    784
67.0     267
45.0     248
153.0    213
        ...
506.0      1
501.0      1
54.0       1
481.0      1
479.0      1
Length: 348, dtype: int64

In [178]:
hotel_df['company'] = hotel_df['company'].astype('object')
hotel_df['company'] = hotel_df['company'].fillna('No Company')

In [179]:
hotel_df['has_company'] = np.where(
    hotel_df['company'] == 'No Company',
    0,
    1
)

In [180]:
hotel_df[hotel_df['has_company'] == 1][['company', 'has_company']]

       company  has_company
18       110.0            1
218      110.0            1
219      110.0            1
220      110.0            1
295      113.0            1
...        ...          ...
119119   451.0            1
119122   451.0            1
119123   451.0            1
119124    72.0            1
119248   485.0            1

[6767 rows x 2 columns]

In [181]:
hotel_df[hotel_df['has_company'] == 0][['company', 'has_company']]

           company  has_company
0       No Company            0
1       No Company            0
2       No Company            0
3       No Company            0
4       No Company            0
...            ...          ...
119385  No Company            0
119386  No Company            0
119387  No Company            0
119388  No Company            0
119389  No Company            0

[112299 rows x 2 columns]

In [182]:
hotel_df.isna().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
name                              0
email                             0
phone-number                      0
credit_card                       0
total_customer                    0
total_stays_nights                0
arrival_date                      0
expected_checkout_date            0
has_company                       0
dtype: int64

In [183]:
hotel_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 119066 entries, 0 to 119389
Data columns (total 41 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119066 non-null  object
 1   is_canceled                     119066 non-null  int64
 2   lead_time                       119066 non-null  int64
 3   arrival_date_year               119066 non-null  int64
 4   arrival_date_month              119066 non-null  object
 5   arrival_date_week_number        119066 non-null  int64
 6   arrival_date_day_of_month       119066 non-null  int64
 7   stays_in_weekend_nights         119066 non-null  int64
 8   stays_in_week_nights            119066 non-null  int64
 9   adults                          119066 non-null  int64
 10  children                        119066 non-null  float64
 11  babies                          119066 non-null  int64
 12  meal                            119066 non-null  object
 13  country                         119066 non-null  object
 14  market_segment                  119066 non-null  object
 15  distribution_channel            119066 non-null  object
 16  is_repeated_guest               119066 non-null  int64
 17  previous_cancellations          119066 non-null  int64
 18  previous_bookings_not_canceled  119066 non-null  int64
 19  reserved_room_type              119066 non-null  object
 20  assigned_room_type              119066 non-null  object
 21  booking_changes                 119066 non-null  int64
 22  deposit_type                    119066 non-null  object
 23  agent                           119066 non-null  object
 24  company                         119066 non-null  object
 25  days_in_waiting_list            119066 non-null  int64
 26  customer_type                   119066 non-null  object
 27  adr                             119066 non-null  float64
 28  required_car_parking_spaces     119066 non-null  int64
 29  total_of_special_requests       119066 non-null  int64
 30  reservation_status              119066 non-null  object
 31  reservation_status_date         119066 non-null  datetime64[ns]
 32  name                            119066 non-null  object
 33  email                           119066 non-null  object
 34  phone-number                    119066 non-null  object
 35  credit_card                     119066 non-null  object
 36  total_customer                  119066 non-null  float64
 37  total_stays_nights              119066 non-null  int64
 38  arrival_date                    119066 non-null  datetime64[ns]
 39  expected_checkout_date          119066 non-null  datetime64[ns]
 40  has_company                     119066 non-null  int64
dtypes: datetime64[ns](3), float64(3), int64(18), object(17)
memory usage: 38.2+ MB

In [184]:
hotel_df.to_csv('clean_hotel_booking.csv', index = False)